### PR TITLE
Implement semester format change

### PR DESCRIPTION
**Pull request by ZMYaro**
This changes semesters from semester_year strings to year.semester floats (e.g., fall_2013 becomes 2013.2) and adds three admin functions to convert member's paid semesters to the new format.

### CODE REVIEW

**Comment by dexw25** [comment]
Tested the schema update functions on a local instance with representative data, no errors, and member page shows members with correct semester data (checked for a few by hand, didn't spot any errors)

/missions page returns error 500, looks like an argument to next_semester() on line 45 was left out in missions.py

**Comment by ZMYaro** [comment]
I can look into that issue tomorrow. Could you post the last few lines of the stack trace?

**Comment by dexw25** [comment]
Sure: 
```
  File "/opt/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/opt/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/home/derek/star-site/missions.py", line 45, in get
    next_semester_date = semester_date(next_semester())
TypeError: next_semester() takes exactly 1 argument (0 given)
```

**Comment by ZMYaro** [comment]
@derekw023: It should be fixed now.

**Comment by ZMYaro** [comment]
@derekw023: Do you have an idea of when you will be ready to approve this?
@AlexFroio or @noblelady: Do you think you might also be able to test this so we can get to +2 before Sunday?

**Comment by dexw25** [comment]
Should get my approval on it tomorrow, I want to run over a few more smaller tests

**Comment by dexw25** [comment]
Tested mission page fixes, a mission with date May 8th 2017 (2017.1) appears on the Fall 2016 (2016.2) mission list, not spring 2017 where it should be

Additionally, a mission with date August 1 2017 (should be in 2017.2) appears in the spring 2017 (2017.1) list
Update: Error lies in semesters.py, due to floating point errors 2017.1-2017 returns 0.09999999 (at least on my system)

**Comment by derekw023** [comment]
Approved, with changes.

**Review by dexw25 — APPROVED** [review]
Approved with changes

**Pull request merged**
