### PR TITLE
Mailing list fix v3

### PR DESCRIPTION
**Pull request by noblelady**
So for every 100 emails there will be a new line character plus a semicolon.

### CODE REVIEW

**Comment by dexw25** [comment]
Tested, the new code does not insert newlines every 100 members. index+1%100 never reaches zero. 
The expression is being evaluated as index+(1%100). That segment should be changed to (index+1)%100

**Comment by noblelady** [comment]
Fixed the equation @derekw023 @zmyaro

**Review by dexw25 — APPROVED** [review]
Looks good

**Review by ZMYaro — APPROVED** [review]
I tweaked some spacing, but otherwise, this looks OK.

**Pull request merged**
